language: node_js
dist: xenial
node_js:
- node
- lts/*
- '10'
before_install:
- sudo apt-get update
- sudo apt-get install -y libsecret-1-dev
script:
- npm run test
- sonar-scanner
install: make install
deploy:
- provider: script
  script: make docker-build && make docker-push
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+$"
    node: lts/*
- provider: npm
  skip_cleanup: true
  edge: true
  email: team_interfaces@twilio.com
  api_key: "$NPM_TOKEN"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+$"
    node: lts/*
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: RfnO47KWRcZhzznK2zU7AQBQd8fmuXQFSCNQ0CpPM/4GywA6XBSVHbnI4uEr7lmEdB2WKktGHtKcfC0H/tCFkxBzovlkiHEsOPrc6/4RsJKrPYjO1qX35ttdiILkmClyo2V8cPOu2m5HhTYddn9wuKN/A7tjjNRHz8ani+CmVBnXMkbyRW5DlY1/q99Y4y2GLMhERyMqNZyeaGDoR4UOl2OuRExBZeN2E7gtUhf5LyCsD/995DQRHx0cJrAZh2tMcubdGOKH0hYVohUFjgeTBOu1Fcwn845i3cXp1IG5cx83EEsNSvcmux96EpMTlu+D7ABjFtUjTFXuDDjXhWGhdC3S3C5/UbVX4tNGbGq2ErSGS4TP8WRPthVyFnvOY2j4jWLmiDDUGyVY8rPsKd2PsO9JDMnL9GCJxwUlK222oAqdkObntm8bEjUk8YODgX7SsgeJ4s5Zp5nKnG/GBiWZAYp2WbiSMltEJiL/jTpAgUMfhVAefgHMi362TC97y/nYcUhGTftMqlx+ca3FlEayV0CTQd9CSjBKuZ/IGeE3qlZbZhWqQMt9gtvNaZ5yToAxNxfxIwJqgdaRlQ5ZJRJESrTXVRIo2v4+9qaofK57trz05oLREyTAUk/8hWGFTcOfXSQw/Up1ycGjtLSLFPuU3PJ7px4lQGfATonv1SgXfrg=
addons:
  sonarcloud:
    token:
      secure: brWWP2cacHcY/Oox17GU0VZyvZb5HsKT1jrnKhEHcge4SdOT6TUBQFf1RonRs3l6ExbNH/bwDeSh01HZlf6wD3a0djeHZqaL74u5Sz47PfEDGFCljeYGhX/AV2UdpLcH0bd36311KMOP8Po1p3M8eneHtoTNTTOHSJ1yQPZ/CRCl2C/TFfv+/+ltLMVpEDIzT7FDqgnZJA3K37VgcuGErCv2SOyshXWNN3fwOoguhPrAyhT8HNNwiy3HNS/0P7Pspx1fzF52pZdpt9lmJ52/6MfxZnHhPEwHqj590Drp3VjByTL2D9HdDcCoPp89vs+O8fElsQI2SOe4+SU2YsEa+gbV+rOY5hk0CUW8dacAatLdig/nOw/wlnitJNMQLLHI8vmKyp2tpYaRfXSgzlhTbR22O3jJnZOWJr8N/MSPBrofTu0y3hyDxk3iqfk6xSHnxoViq605cbQKbl/N1gMK+4jHc65dRLCNVUJzMEETsYYedAMGaosjdYQeEA0xfoJTHS3D5sX/J/3DWjrEbcE+xwsKUl93xZTly04wAD24vzQt1ehLfEjlPSjW5cY5FA89safTlG2YNf4loSY98ruA5JLfJFbKxxSy+4vujk93MdLjFtDspV8bzQl8tqvcJeKSKdnwS+Z8sAdykulkV/zdSXMvyQh8+sTGsIigN3J9pxY=
